version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: emelya
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: emelya_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - emelya-net

  redis:
    image: redis:7
    restart: always
    networks:
      - emelya-net

  app:
    build:
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - emelya-net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - emelya-net

volumes:
  pg_data:
  pgadmin_data:

networks:
  emelya-net: