// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/deposit/approve": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deposit"
                ],
                "summary": "Одобрить депозит",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID депозита",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата одобрения в формате RFC3339",
                        "name": "approved_at",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата блокировки в формате RFC3339",
                        "name": "block_until",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Дневная награда",
                        "name": "daily_reward",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/deposit/by-user": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deposit"
                ],
                "summary": "Получить все депозиты по user_id (только для админа)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/deposit/close": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deposit"
                ],
                "summary": "Закрыть депозит",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID депозита",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/deposit/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-deposit"
                ],
                "summary": "Админ: создать депозит вручную",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID инвестора",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Данные депозита",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_money_deposit_delivery.AdminCreateDepositRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/deposit/delete": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-deposit"
                ],
                "summary": "Админ: удалить депозит (ручное удаление)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID депозита",
                        "name": "deposit_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/deposit/get": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deposit"
                ],
                "summary": "Получить депозит по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID депозита",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/deposit/pending": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-deposit"
                ],
                "summary": "Админ: получить все депозиты в статусе pending",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/reward/by-user": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-reward"
                ],
                "summary": "Админ: получить все награды пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/reward/referral-income": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-reward"
                ],
                "summary": "Админ: начислить доход от реферала",
                "parameters": [
                    {
                        "description": "Данные о вознаграждении",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_money_reward_delivery.AdminCreateReferralRewardRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/user/all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получить всех пользователей",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_user_model.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/user/operations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-user"
                ],
                "summary": "Админ: все операции пользователя (депозиты, выводы, награды)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_money_operation_model.Operations"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/withdrawal/all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-withdrawal"
                ],
                "summary": "Админ: все заявки на вывод",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/withdrawal/approve": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-withdrawal"
                ],
                "summary": "Админ: подтвердить заявку на вывод",
                "parameters": [
                    {
                        "description": "ID заявки",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_money_withdrawal_delivery.AdminApproveWithdrawalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/withdrawal/pending": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-withdrawal"
                ],
                "summary": "Админ: заявки на вывод в статусе pending",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin/withdrawal/reject": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-withdrawal"
                ],
                "summary": "Админ: отклонить заявку на вывод",
                "parameters": [
                    {
                        "description": "ID заявки и причина",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_money_withdrawal_delivery.AdminRejectWithdrawalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/confirm-login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Подтверждение входа",
                "parameters": [
                    {
                        "description": "Телефон и код",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_delivery.ConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login-by-creds": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход по логину и паролю",
                "parameters": [
                    {
                        "description": "Логин и пароль",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_delivery.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Получение текущего пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_user_model.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/request-login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Запрос входа по телефону",
                "parameters": [
                    {
                        "description": "Телефон",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_delivery.PhoneRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/request-register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Запрос на регистрацию",
                "parameters": [
                    {
                        "description": "Данные пользователя",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth_delivery.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/deposit/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deposit"
                ],
                "summary": "Создать заявку на депозит",
                "parameters": [
                    {
                        "description": "Сумма депозита",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_money_deposit_delivery.DepositCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/deposit/my": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deposit"
                ],
                "summary": "Получить все депозиты пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/notify": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifier"
                ],
                "summary": "Отправка произвольного уведомления оператору",
                "parameters": [
                    {
                        "description": "Текст уведомления",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_notifier.NotifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/reward/my": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reward"
                ],
                "summary": "Юзер: получить свои вознаграждения",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/update-profile": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Обновление профиля",
                "parameters": [
                    {
                        "description": "Обновляемые поля",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_user_http.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/withdrawal/my": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "withdrawal"
                ],
                "summary": "Юзер: получить свои заявки на вывод",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/withdrawal/request": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "withdrawal"
                ],
                "summary": "Юзер: создать заявку на вывод",
                "parameters": [
                    {
                        "description": "Данные заявки на вывод",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_money_withdrawal_delivery.CreateWithdrawalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Vovarama1992_emelya-go_internal_money_deposit_model.Deposit": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "approved_at": {
                    "type": "string"
                },
                "block_until": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "daily_reward": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_money_deposit_model.Status"
                },
                "tarif": {
                    "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_money_deposit_model.TarifType"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_Vovarama1992_emelya-go_internal_money_deposit_model.Status": {
            "type": "string",
            "enum": [
                "pending",
                "approved",
                "closed"
            ],
            "x-enum-comments": {
                "StatusApproved": "активный",
                "StatusClosed": "закрыт, разблокирован",
                "StatusPending": "ожидает подтверждения"
            },
            "x-enum-varnames": [
                "StatusPending",
                "StatusApproved",
                "StatusClosed"
            ]
        },
        "github_com_Vovarama1992_emelya-go_internal_money_deposit_model.TarifType": {
            "type": "string",
            "enum": [
                "Легкий старт",
                "Триумф",
                "Максимум"
            ],
            "x-enum-varnames": [
                "TarifLegkiyStart",
                "TarifTriumf",
                "TarifMaksimum"
            ]
        },
        "github_com_Vovarama1992_emelya-go_internal_money_operation_model.Operations": {
            "type": "object",
            "properties": {
                "deposits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_money_deposit_model.Deposit"
                    }
                },
                "rewards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_money_reward_model.Reward"
                    }
                },
                "withdrawals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_money_withdrawal_model.Withdrawal"
                    }
                }
            }
        },
        "github_com_Vovarama1992_emelya-go_internal_money_reward_model.Reward": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "deposit_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "last_accrued_at": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_money_reward_model.RewardType"
                },
                "user_id": {
                    "type": "integer"
                },
                "withdrawn": {
                    "type": "number"
                }
            }
        },
        "github_com_Vovarama1992_emelya-go_internal_money_reward_model.RewardType": {
            "type": "string",
            "enum": [
                "deposit",
                "referral"
            ],
            "x-enum-varnames": [
                "RewardTypeDeposit",
                "RewardTypeReferral"
            ]
        },
        "github_com_Vovarama1992_emelya-go_internal_money_withdrawal_model.Withdrawal": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "approved_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "rejected_at": {
                    "type": "string"
                },
                "reward_id": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_money_withdrawal_model.WithdrawalStatus"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_Vovarama1992_emelya-go_internal_money_withdrawal_model.WithdrawalStatus": {
            "type": "string",
            "enum": [
                "pending",
                "approved",
                "rejected"
            ],
            "x-enum-varnames": [
                "WithdrawalStatusPending",
                "WithdrawalStatusApproved",
                "WithdrawalStatusRejected"
            ]
        },
        "github_com_Vovarama1992_emelya-go_internal_user_model.User": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "cardNumber": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isEmailVerified": {
                    "type": "boolean"
                },
                "isPhoneVerified": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "passwordHash": {
                    "type": "string"
                },
                "patronymic": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "referrerID": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/github_com_Vovarama1992_emelya-go_internal_user_model.UserRole"
                }
            }
        },
        "github_com_Vovarama1992_emelya-go_internal_user_model.UserRole": {
            "type": "string",
            "enum": [
                "user",
                "admin"
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleAdmin"
            ]
        },
        "internal_auth_delivery.ConfirmRequest": {
            "type": "object",
            "required": [
                "code",
                "phone"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_auth_delivery.LoginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "internal_auth_delivery.PhoneRequest": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_auth_delivery.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 50
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 50
                },
                "patronymic": {
                    "type": "string",
                    "maxLength": 50
                },
                "phone": {
                    "type": "string"
                },
                "referrerId": {
                    "type": "integer"
                }
            }
        },
        "internal_money_deposit_delivery.AdminCreateDepositRequest": {
            "type": "object",
            "required": [
                "amount",
                "approved_at",
                "block_until",
                "created_at",
                "daily_reward",
                "tarif",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "approved_at": {
                    "type": "string"
                },
                "block_until": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "daily_reward": {
                    "type": "number"
                },
                "tarif": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_money_deposit_delivery.DepositCreateRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                }
            }
        },
        "internal_money_reward_delivery.AdminCreateReferralRewardRequest": {
            "type": "object",
            "required": [
                "amount",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_money_withdrawal_delivery.AdminApproveWithdrawalRequest": {
            "type": "object",
            "required": [
                "withdrawal_id"
            ],
            "properties": {
                "withdrawal_id": {
                    "type": "integer"
                }
            }
        },
        "internal_money_withdrawal_delivery.AdminRejectWithdrawalRequest": {
            "type": "object",
            "required": [
                "reason",
                "withdrawal_id"
            ],
            "properties": {
                "reason": {
                    "type": "string"
                },
                "withdrawal_id": {
                    "type": "integer"
                }
            }
        },
        "internal_money_withdrawal_delivery.CreateWithdrawalRequest": {
            "type": "object",
            "required": [
                "amount",
                "reward_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "reward_id": {
                    "type": "integer"
                }
            }
        },
        "internal_notifier.NotifyRequest": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "example": "Имя: Иванов Иван\nТелефон: +7900...\nТариф: Премиум"
                }
            }
        },
        "internal_user_http.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "card_number": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
