basePath: /api
definitions:
  auth.ConfirmRequest:
    properties:
      code:
        example: "1234"
        type: string
      phone:
        example: "79001112233"
        type: string
    type: object
  auth.LoginRequest:
    properties:
      login:
        example: user123
        type: string
      password:
        example: pass1234
        type: string
    type: object
  auth.PhoneRequest:
    properties:
      phone:
        example: "79001112233"
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      email:
        example: ivan@example.com
        type: string
      first_name:
        example: Иван
        type: string
      last_name:
        example: Иванов
        type: string
      patronymic:
        example: Иванович
        type: string
      phone:
        example: "79001112233"
        type: string
      referrerId:
        type: integer
    type: object
  notifier.NotifyRequest:
    properties:
      text:
        example: |-
          Имя: Иванов Иван
          Телефон: +7900...
          Тариф: Премиум
        type: string
    type: object
  user.RequestWithdrawRequest:
    properties:
      amount:
        example: 1500
        type: number
    type: object
  user.UpdateProfileRequest:
    properties:
      card_number:
        example: "1234567812345678"
        type: string
    type: object
  user.User:
    properties:
      cardNumber:
        description: ← вот это
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      isEmailVerified:
        type: boolean
      isPhoneVerified:
        type: boolean
      lastName:
        type: string
      login:
        type: string
      passwordHash:
        type: string
      patronymic:
        type: string
      phone:
        type: string
      referrerID:
        type: integer
    type: object
host: emelia-invest.com
info:
  contact: {}
  description: API для регистрации и логина
  title: Emelya API
  version: "1.0"
paths:
  /api/auth/confirm-login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Телефон и код
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.ConfirmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Подтверждение входа
      tags:
      - auth
  /api/auth/login-by-creds:
    post:
      consumes:
      - application/json
      parameters:
      - description: Логин и пароль
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Вход по логину и паролю
      tags:
      - auth
  /api/auth/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получение текущего пользователя
      tags:
      - auth
  /api/auth/request-login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Телефон
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.PhoneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Запрос входа по телефону
      tags:
      - auth
  /api/auth/request-register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные пользователя
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Запрос на регистрацию
      tags:
      - auth
  /api/notify:
    post:
      consumes:
      - application/json
      parameters:
      - description: Текст уведомления
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/notifier.NotifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Отправка произвольного уведомления оператору
      tags:
      - notifier
  /api/user/request-withdraw:
    post:
      consumes:
      - application/json
      parameters:
      - description: Сумма вывода
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.RequestWithdrawRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Запрос на вывод средств
      tags:
      - user
  /api/user/update-profile:
    post:
      consumes:
      - application/json
      parameters:
      - description: Обновляемые поля
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновление профиля
      tags:
      - user
schemes:
- https
swagger: "2.0"
